TOPDIR ?= ../..
include $(TOPDIR)/.config

$(BREWTRONIC_SUPPORT)_SRC += services/brewtronic/brewtronic.c
$(BREWTRONIC_SUPPORT)_ECMD_SRC += services/brewtronic/ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
