TOPDIR ?= ../..
include $(TOPDIR)/.config

$(APP_SAMPLE_SUPPORT)_SRC += services/brewtronic/brewtronic.c
$(APP_SAMPLE_SUPPORT)_ECMD_SRC += services/brewtronic/ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
